apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api-service
  labels:
    app: kubernetes-demo-api
spec:
  selector:
    app: kubernetes-demo-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 # Port container is listening on
  type: NodePort # Use LoadBalancer when deploying on Cloud